<%@ page contentType="text/html;charset=euc-kr"%>
<meta name="viewport" content="width=divice-width", initial-scale="1">
<link rel="stylesheet" href="../css/bootstrap.css">
<!-- 세션정보 및 전역변수 -->
<%
String ID   = (String)session.getAttribute("ID");
String name = (String)session.getAttribute("name");
%>


<%@ include file="../include/menu.inc" %>




<h1 align="center">
<div style='line-height:140%'>
<p style="font-family:'나눔고딕'; font-size:75px;">
It' Shoe!
</p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
이슈가되다.
</h1>
</div>
